name: Destroy Infra

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  destroy-stage2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/stage2-ecs
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - run: terraform destroy -auto-approve

  destroy-stage1:
    runs-on: ubuntu-latest
    needs: destroy-stage2
    defaults:
      run:
        working-directory: ./terraform/stage1-infra
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - run: terraform destroy -auto-approve