name: Full Infra + App Deploy

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPO_NAME: ${{ vars.ECR_REPO_NAME }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  # -----------------------------------
  # Stage 1: Provision base infrastructure
  # -----------------------------------
  infra:
    name: Provision Infra
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/stage1-infra
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve

  # -----------------------------------
  # Stage 2: Build & Push Docker Image
  # -----------------------------------
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: infra
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Set ECR repo URI
        run: echo "ECR_REPO=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}" >> $GITHUB_ENV

      - name: Build and push Docker image to ECR
        uses: docker/build-push-action@v6
        env:
          IMAGE_TAG_SHA: ${{ github.sha }}  # Tag for the specific commit
          IMAGE_TAG_LATEST: latest          # Generic 'latest' tag
        with:
          context: ./application           # Path to the Docker context
          push: true                       # Push the image to the registry
          tags: |                          # List of tags for the image
            ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG_LATEST }}
            ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG_SHA }}